# create a docker-compose.yml file
version: "2"
services:
  web:
    image: glr.honestbee.com/trieunk/vrp_public:latest
    build: .
    volumes:
      - ./:/app
      - apidata:/var/data
    environment:
      - PORT=9999
    ports:
      - "80:9999"
volumes:
  apidata: